# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Discord-bot-deploy

on:
  push:
    branches: [CI]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        with:
          script: |
            npm install
            npm run deploy -- -m "Deploy React app to GitHub Pages  testing"
